# Generated by Django 5.1.1 on 2024-09-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
